# Generated by Django 5.1.2 on 2024-11-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(max_length=100)),
                ('Residence', models.TextField(max_length=100)),
                ('Alert', models.BooleanField(default=False, help_text='if checked means its an alert else its an event')),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Description', models.TextField(max_length=300)),
            ],
        ),
    ]
