Here is a step-by-step guide on how to add a welcome message on the home screen whenever a user logs into the website:

**1. Which files need modifications?**

* `backend/api/admin.py`: to register a new model for the welcome message
* `backend/api/migrations/0002_alertevent.py`: to create a new model for the welcome message
* `backend/api/apps.py`: to add the new model to the app's models
* `backend/api/templates`: to create a new template for the welcome message

**2. What changes should be made?**

**backend/api/admin.py**
```
from django.contrib import admin

from api.models import *

# Register your models here.
admin.site.register(ResidenceGroup)
admin.site.register(Profile)
admin.site.register(AlertEvent)
admin.site.register(Residence)
admin.site.register(WelcomeMessage)  # <--- new model registration
```

**backend/api/migrations/0002_alertevent.py**
```
# Generated by Django 5.1.2 on 2024-11-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(max_length=100)),
                ('Residence', models.TextField(max_length=100)),
                ('Alert', models.BooleanField(default=False, help_text='if checked means its an alert else its an event')),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Description', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='WelcomeMessage',  # <--- new model creation
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=200)),
            ],
        ),
    ]
```

**backend/api/apps.py**
```
from django.apps import AppConfig


class ApiConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'api'
    verbose_name = 'API'  # <--- add the new model to the app's models
    models = ['api.models', 'api.models.WelcomeMessage']  # <--- add the new model
```

**backend/api/templates**: create a new file `welcome_message.html` with the following content:
```
<h1>Welcome to our website!</h1>
<p>{{ welcome_message.message }}</p>
```

**3. Any additional dependencies or configurations required?**

No additional dependencies or configurations are required. The above changes should be sufficient to add a welcome message on the home screen whenever a user logs into the website.