# Generated by Django 5.1.2 on 2024-11-05 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alertevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertevent',
            name='Alert',
        ),
        migrations.AddField(
            model_name='alertevent',
            name='Event',
            field=models.BooleanField(default=True, help_text='if unchecked means its an alert else its an event'),
        ),
    ]
