# Generated by Django 5.1.2 on 2024-11-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_alertevent_alert_alertevent_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isVerified',
            field=models.BooleanField(default=False, help_text='This field is checked by the admin and only when the admin checks this field a user can login to the portal'),
        ),
    ]
