# Generated by Django 5.1.2 on 2024-11-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_profile_residence_profile_adminpincode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertevent',
            name='Completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alertevent',
            name='Venue',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
